<a href="https://colab.research.google.com/github/CarrieIsPop/MAR-IA/blob/main/INFO.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
#pip install numpy

ARRAYS DE 1 DIMENSION

In [ ]:
array_1d = np.array([10, 20, 30])
print(array_1d)

[10 20 30]


In [ ]:
array_1d

array([10, 20, 30])

ARRAYS DE 2 DIMENSIONES

In [ ]:
array_2d = np.array([(10,20,30),(50,60,70)])
print(array_2d)

[[10 20 30]
 [50 60 70]]


ARRAYS DE 3 DIMENSIONES

In [ ]:
array_3d = np.array([(10, 20, 30),(40, 50, 60),(70, 80, 90)], dtype=float)
array_3d

array([[10., 20., 30.],
       [40., 50., 60.],
       [70., 80., 90.]])

ARRAY CON CEROS DE 3 FILAS Y 4 COLUMNAS

In [ ]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
print(np.zeros((4, 5)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


ARRAY DE 1 CON DOS DIMENSIONES DE 4 FILAS Y 5 COLUMNAS

In [ ]:
np.ones((2, 4, 5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

ARRAYS CON INTERVALOS Y SALTOS

In [ ]:
np.arange(11, 30, 2)

array([11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

ARRAY CON INTERVALOS Y DIVISIONES

In [ ]:
np.linspace(0, 4, 7)

array([0.        , 0.66666667, 1.33333333, 2.        , 2.66666667,
       3.33333333, 4.        ])

ARRAYS CON VALORES DADOS

In [ ]:
np.full((3, 3), 7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

ARRAY CON MATRIZ IDENTIDAD, DIAGONAL DE UNOS

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

ARRAY CON VALORES ALEATORIOS 0-1

In [ ]:
np.random.random((4, 4))

array([[0.69989908, 0.27598912, 0.44030102, 0.66375047],
       [0.04568867, 0.55503278, 0.26949896, 0.33134757],
       [0.97259923, 0.67440139, 0.68339783, 0.15122542],
       [0.18730509, 0.71285266, 0.43723202, 0.6526817 ]])

ARRAY DE NUMEROS VACIOS 4*3

In [ ]:
np.empty((4, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

GRABAR Y CARGAR

In [ ]:
#Grabar
np.save('my_array_2d', array_2d)

In [ ]:
#Cargar
my_array = np.load('my_array_2d.npy')
my_array

array([[10, 20, 30],
       [50, 60, 70]])

GRABAR Y CARGAR FICHEROS DE TEXTO

In [ ]:
#Grabar el fichero de texo
np.savetxt('my_array_2d.txt', array_2d, delimiter=' ')

In [ ]:
#Cargar de fichero de texto
np.loadtxt('my_array_2d.txt')

array([[10., 20., 30.],
       [50., 60., 70.]])

TIPOS DE DATOS

In [ ]:
#ENTEROS
np.int64

numpy.int64

In [ ]:
#DECIMAL, FLOTANTES
np.float64

numpy.float64

In [ ]:
#COMPLEJOS
np.complex64

numpy.complex64

In [ ]:
#BOOLEANOS
np.bool_

numpy.bool

In [ ]:
#OBJETOS
np.object_

numpy.object_

In [ ]:
#CADENAS DE TEXTO
np.strings

<module 'numpy.strings' from '/usr/local/lib/python3.11/dist-packages/numpy/strings/__init__.py'>

In [ ]:
np.bytes_

numpy.bytes_

PROPIEDADES Y CARACTERISTICAS DE ENTORNOS

In [ ]:
array_3d

array([[10., 20., 30.],
       [40., 50., 60.],
       [70., 80., 90.]])

In [ ]:
array_3d.shape

(3, 3)

In [ ]:
#LONGITUD
len(array_3d)

3

In [ ]:
#NUMERO DE DIMENSIONES
array_3d.ndim

2

In [ ]:
array_5d = np.array([[[[[1]], [[2]]], [[[3]], [[4]]], [[[5]], [[6]]], [[[7]], [[8]]], [[[9]], [[10]]]]], ndmin=5)
print(array_5d)

[[[[[ 1]]

   [[ 2]]]


  [[[ 3]]

   [[ 4]]]


  [[[ 5]]

   [[ 6]]]


  [[[ 7]]

   [[ 8]]]


  [[[ 9]]

   [[10]]]]]


In [ ]:
array_5d.ndim

5

In [ ]:
#TIPOS DE DATOS
array_3d.dtype

dtype('float64')

In [ ]:
array_3d.dtype.name

'float64'

In [ ]:
#CONVERTIR DE UN TIPO DE DATO A OTRO TIPO DE DATO
array_3d.astype(int)

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

OPERADORES MATEMATICOS

In [ ]:
#ARRAY DE EJEMPLOS
array1 = np.random.random((4, 4))
array1

array([[0.21649176, 0.55701407, 0.38032676, 0.77972859],
       [0.76491203, 0.9280375 , 0.15135794, 0.87792324],
       [0.98985312, 0.68576144, 0.18182032, 0.0882285 ],
       [0.79558793, 0.42287882, 0.75372384, 0.91786839]])

In [ ]:
array2 = np.random.random((4, 4))
array2

array([[0.86687809, 0.27224441, 0.73009429, 0.29252134],
       [0.70634083, 0.78787131, 0.25279326, 0.66841159],
       [0.71446419, 0.77552319, 0.60430413, 0.97739149],
       [0.69954762, 0.99604907, 0.47220527, 0.22985173]])

In [ ]:
array3 = np.random.random((4, 4))
array3

array([[0.13457862, 0.37490748, 0.76859272, 0.43994569],
       [0.37056834, 0.07353228, 0.44635969, 0.02998595],
       [0.90082968, 0.55390251, 0.40518753, 0.6294463 ],
       [0.6034271 , 0.27295236, 0.02593352, 0.72095108]])

In [ ]:
#SUMA
array4 = array1 + array2 + array3
print(array4)

[[1.65075887 1.80771578 1.12679227 1.93614058]
 [2.25657794 2.51293481 0.52651976 1.74568203]
 [2.69635363 1.69732781 0.81679929 1.56784888]
 [2.17475731 2.2859499  1.76593366 1.56003487]]


In [ ]:
#RESTA
array4 = array1 - array2 - array3
print(array4)

[[-0.8380583   0.1331257  -0.62744192  0.25912001]
 [-0.48171739 -0.59100793 -0.13969759 -0.37730241]
 [-0.43182569 -0.62158565 -0.53235858 -0.97539677]
 [-0.46051133 -0.99437831 -0.0743938   0.47704302]]


In [ ]:
array4 = np.subtract(array1, array2, array3)
print(array4)

[[-0.65038634  0.28476967 -0.34976753  0.48720726]
 [ 0.0585712   0.1401662  -0.10143532  0.20951166]
 [ 0.27538892 -0.08976175 -0.42248381 -0.88916298]
 [ 0.09604031 -0.57317025  0.28151856  0.68801666]]


In [ ]:
#MULTIPLICACION
array4 = np.multiply(array1, array2, array3)
print(array4)

[[0.18767196 0.15164397 0.2776744  0.22808725]
 [0.5402886  0.73117412 0.03826227 0.58681407]
 [0.70721461 0.53182389 0.10987477 0.08623379]
 [0.55655164 0.42120806 0.35591237 0.21097364]]


In [ ]:
#DIVISION
array4 = np.divide(array1, array2, array3)
print(array4)

[[0.24973726 2.04600742 0.52092828 2.66554435]
 [1.08292201 1.17790494 0.598742   1.31344707]
 [1.38544818 0.88425652 0.30087553 0.09026936]
 [1.13728917 0.42455621 1.59617836 3.99330641]]


In [ ]:
#EXPONENTES
array4 = np.exp(array1)
print(array4)

[[1.24171285 1.74545292 1.46276248 2.18088028]
 [2.14880534 2.52954009 1.16341302 2.40589805]
 [2.69083921 1.98528293 1.19939867 1.09223767]
 [2.21574331 1.52634933 2.12489807 2.50394727]]


In [ ]:
#SENO
array4 = np.sin(array1)
print(array4)

[[0.2148046  0.52865399 0.3712239  0.70308645]
 [0.69247354 0.80044515 0.15078069 0.76941401]
 [0.83594538 0.6332625  0.18082019 0.08811408]
 [0.7142752  0.41038738 0.68435872 0.79430844]]


In [ ]:
#COSENO
array4 = np.cos(array1)
print(array4)

[[0.97665704 0.84883741 0.92854338 0.71110439]
 [0.72144328 0.59940601 0.98856724 0.63875041]
 [0.54881265 0.77393708 0.98351617 0.99611039]
 [0.69986494 0.91191129 0.72914549 0.60751469]]


In [ ]:
#LOGARITMO
array4 = np.log(array1)
print(array4)

[[-1.53020281 -0.58516477 -0.9667245  -0.24880938]
 [-0.26799444 -0.07468313 -1.88810776 -0.13019611]
 [-0.01019871 -0.37722547 -1.70473632 -2.42782521]
 [-0.2286739  -0.86066961 -0.28272924 -0.08570126]]


COMPARACIONES ENTRE MATRICES

In [ ]:
# ==
array1 == array2

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
# <
array1 < 0.5

array([[ True, False,  True, False],
       [False, False,  True, False],
       [False, False,  True,  True],
       [False,  True, False, False]])

In [ ]:
# >
array1 > 0.5

array([[False,  True, False,  True],
       [ True,  True, False,  True],
       [ True,  True, False, False],
       [ True, False,  True,  True]])

In [ ]:
# <= / >=
array2 <= 0.6

array([[False,  True, False,  True],
       [False, False,  True, False],
       [False, False, False, False],
       [False, False,  True,  True]])

In [ ]:
array2 >= 0.6

array([[ True, False,  True, False],
       [ True,  True, False,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False]])

ESTADISTICAS Y FUNCIONES

In [ ]:
array6 = np.random.random((5, 5))
array6

array([[0.55771642, 0.33482439, 0.59152061, 0.26910535, 0.79941345],
       [0.46542389, 0.92455195, 0.54330924, 0.5151736 , 0.68813207],
       [0.78952715, 0.18865819, 0.02368247, 0.92581823, 0.08735576],
       [0.84798314, 0.55683703, 0.65205918, 0.8685013 , 0.52918677],
       [0.98668328, 0.21366973, 0.61399476, 0.42040066, 0.14062893]])

In [ ]:
#SUMA DE ELEMENTOS
sumaTotal = np.sum(array6)
print(sumaTotal)

13.534157560895048


In [ ]:
#VALOR MINIMO - MAXIMO
print(np.min(array6))
print(np.max(array6))

0.02368247153816272
0.9866832765237129


In [ ]:
#MAXIMO POR FILA O COLUMNA
print(np.max(array6, axis=0))
print(np.max(array6, axis=1))

[0.98668328 0.92455195 0.65205918 0.92581823 0.79941345]
[0.79941345 0.92455195 0.92581823 0.8685013  0.98668328]


In [ ]:
#FILA ACUMULADA
array6.cumsum(axis=1)

array([[0.55771642, 0.89254081, 1.48406142, 1.75316678, 2.55258022],
       [0.46542389, 1.38997585, 1.93328509, 2.44845869, 3.13659076],
       [0.78952715, 0.97818534, 1.00186781, 1.92768604, 2.0150418 ],
       [0.84798314, 1.40482017, 2.05687935, 2.92538065, 3.45456742],
       [0.98668328, 1.20035301, 1.81434777, 2.23474842, 2.37537736]])

In [ ]:
#MEDIA
np.mean(array6)

np.float64(0.541366302435802)

In [ ]:
#MEDIANA
np.median(array6)

np.float64(0.5568370297365893)

In [ ]:
#DESVIACION
np.std(array6)

np.float64(0.27340515653961034)